---
- name: Ansible configuration to ansible host environment
  hosts: all
  remote_user: root
  become: true
  become_user: root

  roles:
    - { role: mongo }
    - { role: deno }
    - { role: tg_bot }
    