---
# Install and configure deno

- name: Download deno installation script
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: /tmp/deno_install.sh
    mode: '0750'

- name: Install latest deno
  ansible.builtin.script: /tmp/deno_install.sh -s 1.9.0

- name: Remove deno installation script
  ansible.builtin.file:
    path: /tmp/deno_install.sh
    state: absent