---
# Install and configure deno

- name: Install zip (used for deno)
  ansible.builtin.apt:
    name: zip
    update_cache: yes

- name: Download deno installation script
  ansible.builtin.get_url:
    url: https://deno.land/x/install/install.sh
    dest: /tmp/deno_install.sh
    mode: '0750'

- name: Install latest deno
  ansible.builtin.script: /tmp/deno_install.sh v1.9.0

- name: Remove deno installation script
  ansible.builtin.file:
    path: /tmp/deno_install.sh
    state: absent